# Generated by Django 2.1.7 on 2019-08-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('ME', 'medical'), ('EU', 'education'), ('SP', 'startup')], max_length=2),
        ),
    ]
