# Generated by Django 2.2.3 on 2019-08-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('SP', 'startup'), ('ME', 'medical'), ('EU', 'education')], max_length=2),
        ),
    ]
