# Generated by Django 2.2.3 on 2019-08-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20190802_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('SP', 'startup'), ('EU', 'education'), ('ME', 'medical')], max_length=2),
        ),
    ]
