# Generated by Django 2.1.7 on 2019-08-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20190817_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.BooleanField(choices=[(True, 'accepted'), (False, 'not accepted')], null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('SP', 'startup'), ('ME', 'medical'), ('EU', 'education')], max_length=2),
        ),
    ]
