# Generated by Django 2.2.3 on 2019-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20190802_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.BooleanField(choices=[(True, 'accepted'), (False, 'not accepted')], null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('ME', 'medical'), ('EU', 'education'), ('SP', 'startup')], max_length=2),
        ),
    ]
