# Generated by Django 2.1.7 on 2019-08-17 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20190817_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('EU', 'education'), ('ME', 'medical'), ('SP', 'startup')], max_length=2),
        ),
    ]
