# Generated by Django 2.2.4 on 2019-08-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_auto_20190817_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donate_type',
            field=models.CharField(choices=[('GD', 'Giving Donation to Others'), ('RD', 'Receiving Donation from Others')], default='GD', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('ME', 'medical'), ('SP', 'startup'), ('EU', 'education')], max_length=2),
        ),
    ]
