# Generated by Django 2.2.4 on 2019-08-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20190818_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='transaction_status',
            field=models.BooleanField(choices=[(True, 'Transaction completed'), (False, 'Transaction not completed')], default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donate_type',
            field=models.CharField(choices=[('RD', 'Receiving Donation from Others'), ('GD', 'Giving Donation to Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('EU', 'education'), ('SP', 'startup'), ('ME', 'medical')], max_length=2),
        ),
    ]
