# Generated by Django 2.2.4 on 2019-08-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_auto_20190819_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donate_type',
            field=models.CharField(choices=[('RD', 'Receiving Donations'), ('GD', 'Giving Donation')], max_length=2),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('ME', 'medical'), ('SP', 'startup'), ('EU', 'education')], max_length=2),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.BooleanField(choices=[(False, 'not accepted'), (True, 'accepted')], null=True),
        ),
    ]
