# Generated by Django 2.2.4 on 2019-08-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190802_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='nid',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'g_donate'), (1, 'r_donate')], null=True),
        ),
    ]
