# Generated by Django 2.2.3 on 2019-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190802_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'r_donate'), (1, 'g_donate')], null=True),
        ),
    ]
