# Generated by Django 2.2.3 on 2019-08-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190802_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'g_donate'), (2, 'r_donate')], null=True),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
