# Generated by Django 2.2.3 on 2019-08-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190802_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'r_donate'), (1, 'g_donate')], null=True),
        ),
    ]
